<?php
// auto-generated by sfSecurityConfigHandler
// date: 2025/04/23 09:49:11
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 'admin',
  ),
);
