<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2025/04/22 11:44:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost:3307;dbname=jobeet',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
