<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/04/23 09:49:54
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
