<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2025/04/23 09:49:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost:3307;dbname=jobeet',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
